### ISSUE TITLE
How do I reload any picker view?

### ISSUE THREAD

**Issue by kunass2** [filipealva/PickerView#22]
Is there a way to refresh number of rows?

**Comment by aminiz** [comment]
For this particular library, you can use:
`pickerView.tableView.reloadData()`

**Comment by kunass2** [comment]
ok, thanks

**Comment by y4nnick** [comment]
I can't call the reloadData Method:

If gives me a `Ambiguous reference to member 'tableView(_:numberOfRowsInSection:)'`
with the code `self.setsBpreset.tableView.reloadData()`

Is there a way to call it?

**Comment by filipealva** [comment]
Hi @y4nnick!

On the latest release I made `tableView`a fileprivate property of `PickerView` and forgot to add a method to expose the ability to reload the picker. I'll fix it and release a new version later today.

Thank you for reporting!

**Comment by y4nnick** [comment]
Thanks for the quick response and this cool custom view.
Looking forward to the new version!

**Comment by filipealva** [comment]
@y4nnick You're welcome. I'm happy you liked it :) 

Man, I'm really sorry but I can't release the version today as I said. Today was a big release day in my company and could not dig into it because of that (now is 12AM here and I just stopped working, hehe)

I'll release it early tomorrow.

**Comment by filipealva** [comment]
Hey @y4nnick, it's deployed! 

Sorry again for the delay. Please let me know if everything is working properly.

![captura de tela 2017-03-26 as 22 28 43](https://cloud.githubusercontent.com/assets/6117280/24337461/ba962ad4-1273-11e7-9dde-73c85864ead9.png)

**Comment by y4nnick** [comment]
Thanks, i will test it today and let you know :)

**Comment by y4nnick** [comment]
How can i use the new version? It seems that the pod is not found.
I added `pod 'PickerView', '~> 0.3.1'` to my Podfile

![bildschirmfoto 2017-05-02 um 18 25 14](https://cloud.githubusercontent.com/assets/5279469/25627966/b7ed1c1c-2f64-11e7-94b2-81ec14ab65e8.png)

**Comment by y4nnick** [comment]
I also cleaned the pod cache and tried to remove it from Podfile and inserting it again.

**Comment by filipealva** [comment]
Did you tried running "pod repo update" command and then running "pod
install" again?

It should solve this issue

Em ter, 2 de mai de 2017 às 13:28, Yannick <notifications@github.com>
escreveu:

**Comment by y4nnick** [comment]
Thanks for your quick response! Now i have the right version.

Sadly the picker views still not reload correctly:

![screen shot 2017-05-02 at 19 09 17](https://cloud.githubusercontent.com/assets/5279469/25629743/e8f5f09e-2f6a-11e7-819a-7383bdb5de24.png)

My Code for reseting: 
pointsApreset.reloadPickerView()
setsApreset.reloadPickerView()
pointsBpreset.reloadPickerView()
setsBpreset.reloadPickerView()
            
pointsApreset.currentSelectedRow = 0
setsApreset.currentSelectedRow = 0
pointsBpreset.currentSelectedRow = 0
setsBpreset.currentSelectedRow = 0

I also tried it with 
self.pointsApreset.setNeedsLayout or
self.pointsApreset.setNeedsDisplay
but still the same result.

**Comment by y4nnick** [comment]
It seems that the correct number gets selected (bold font) but the scrolling position doesn't get reseted.

**Comment by y4nnick** [comment]
@filipealva any ideas? :)

**Comment by filipealva** [comment]
@y4nnick I'm not able to reproduce this issue :( can you provide a project with the example of this scenario so I can verify?

thanks
